"""Velice project manifest (velice.toml) and project directory handling."""
import os
import sys
from velice import toml


PROJECT_FILES = ("velice.toml",)
PROJECT_DIRS = ("src", "packages", "tests", "docs", "build", "assets")
PROJECT_ROOT_DOCS = ("README.md", "LICENSE", "CHANGELOG.md")


class ManifestError(Exception):
    pass


class Project:
    def __init__(self, root):
        self.root = os.path.abspath(root)
        self.manifest_path = os.path.join(self.root, "velice.toml")
        self.data = {}
        self.lock = {}

    # ── discovery ──────────────────────────────────────────────────────
    @classmethod
    def find(cls, start=None):
        """Walk up from `start` looking for a velice.toml project root."""
        cur = os.path.abspath(start or os.getcwd())
        while True:
            if os.path.exists(os.path.join(cur, "velice.toml")):
                return cls(cur)
            parent = os.path.dirname(cur)
            if parent == cur:
                return None
            cur = parent

    def exists(self):
        return os.path.exists(self.manifest_path)

    def load(self):
        if not self.exists():
            raise ManifestError(f"no velice.toml found in {self.root}")
        self.data = toml.load(self.manifest_path)
        self.lock = self._read_lock()
        return self

    # ── accessors ──────────────────────────────────────────────────────
    @property
    def name(self):
        return self.data.get("name", os.path.basename(self.root))

    @property
    def version(self):
        return str(self.data.get("version", "0.1.0"))

    @property
    def entry(self):
        entry = self.data.get("entry", "src/main.velice")
        return os.path.join(self.root, entry)

    @property
    def dependencies(self):
        deps = self.data.get("dependencies", [])
        if isinstance(deps, dict):
            return [f"{k}@{v}" if str(v) not in ("*", "") else k for k, v in deps.items()]
        return list(deps)

    def src_dir(self):
        return os.path.join(self.root, "src")

    def build_dir(self):
        return os.path.join(self.root, "build")

    def packages_dir(self):
        return os.path.join(self.root, "packages")

    def tests_dir(self):
        return os.path.join(self.root, "tests")

    def docs_dir(self):
        return os.path.join(self.root, "docs")

    def lock_path(self):
        return os.path.join(self.root, "velice.lock")

    def _read_lock(self):
        path = self.lock_path()
        if os.path.exists(path):
            return toml.load(path)
        return {}

    def write_lock(self, packages):
        lines = ["# velice.lock — generated by velice. Do not edit.", ""]
        lines.append(f'name = "{self.name}"')
        lines.append(f'version = "{self.version}"')
        lines.append("")
        lines.append("[dependencies]")
        for name, info in sorted(packages.items()):
            lines.append(f'{name} = {{ version = "{info["version"]}", '
                         f'sha256 = "{info.get("sha256", "")}", '
                         f'source = "{info.get("source", "registry")}" }}')
        with open(self.lock_path(), "w") as f:
            f.write("\n".join(lines) + "\n")

    def write_manifest(self):
        lines = [
            f'name = "{self.data.get("name", "MyApp")}"',
            f'version = "{self.data.get("version", "0.1.0")}"',
        ]
        for key in ("author", "description", "license", "language", "repository",
                    "homepage", "entry"):
            if self.data.get(key):
                lines.append(f'{key} = "{self.data[key]}"')
        if self.data.get("keywords"):
            kws = ", ".join(f'"{k}"' for k in self.data["keywords"])
            lines.append(f"keywords = [{kws}]")
        deps = self.data.get("dependencies", [])
        if deps:
            lines.append("")
            lines.append('dependencies = [')
            for d in deps:
                lines.append(f'    "{d}",')
            lines.append("]")
        with open(self.manifest_path, "w") as f:
            f.write("\n".join(lines) + "\n")


# ── scaffolding ────────────────────────────────────────────────────────
DEFAULT_SRC_MAIN = """\
# {name} v{version}
print("Hello from {name}!")
"""


def scaffold_project(root, name=None):
    """Create the standard Velice project layout in `root`."""
    root = os.path.abspath(root)
    name = name or os.path.basename(root.rstrip("/"))
    if not re_ident(name):
        name = "".join(c if c.isalnum() or c in "_-" else "_" for c in name) or "MyApp"
    for d in PROJECT_DIRS:
        os.makedirs(os.path.join(root, d), exist_ok=True)
    manifest = os.path.join(root, "velice.toml")
    if not os.path.exists(manifest):
        with open(manifest, "w") as f:
            f.write(f'name = "{name}"\n'
                    f'version = "0.1.0"\n'
                    f'description = "A new Velice project"\n'
                    f'license = "MIT"\n'
                    f'language = "1.0"\n'
                    f'entry = "src/main.velice"\n')
    main = os.path.join(root, "src", "main.velice")
    if not os.path.exists(main):
        with open(main, "w") as f:
            f.write(DEFAULT_SRC_MAIN.format(name=name, version="0.1.0"))
    for doc in PROJECT_ROOT_DOCS:
        path = os.path.join(root, doc)
        if not os.path.exists(path):
            with open(path, "w") as f:
                f.write(f"# {name}\n\n")
    return Project(root)


def re_ident(name):
    return bool(name and name.replace("-", "_").replace("_", "x").isalnum())
