name=Datapro
slug=info
language=Java
status=DEVELOPMENT
main=App1
description=Local workspace analytics dashboard.
source=apps/info
type=data
json=info.json
logs=logs/info.log
files=1
directories=0
size=42297
generated=Aug 17, 11:32:56
