name=DataDocs
slug=datadocs
language=Java
status=ACTIVE
main=DataDocs
description=Lightweight Swing text editor.
source=apps/datadocs
type=data
json=datadocs.json
logs=logs/datadocs.log
files=2
directories=1
size=96652
generated=Aug 17, 11:32:56
