package pages;
import components.Ui; import java.awt.*; import javax.swing.*; import model.AppStore;
@SuppressWarnings({"serial", "this-escape"})
public class Dashboard extends JPanel {
 private final AppStore store=AppStore.get(); private final JPanel stats=new JPanel(new GridLayout(1,4,14,0)); private final JPanel activity=new JPanel();
 public Dashboard(){setLayout(new BorderLayout(0,22));setBackground(Ui.BG);setBorder(BorderFactory.createEmptyBorder(28,30,28,30));add(Ui.header("Dashboard","A quick view of your workspace."),BorderLayout.NORTH);JPanel body=new JPanel(new BorderLayout(0,22));body.setOpaque(false);stats.setOpaque(false);body.add(stats,BorderLayout.NORTH);activity.setLayout(new BoxLayout(activity,BoxLayout.Y_AXIS));activity.setBackground(Color.WHITE);activity.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(229,231,239)),BorderFactory.createEmptyBorder(20,22,20,22)));body.add(activity);add(body);store.listen(this::refresh);refresh();}
 private JPanel card(String label,int value,Color color){JPanel p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBackground(Color.WHITE);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0,4,0,0,color),BorderFactory.createEmptyBorder(16,18,16,10)));JLabel n=new JLabel(String.valueOf(value));n.setFont(new Font("SansSerif",Font.BOLD,30));n.setForeground(Ui.INK);p.add(n);p.add(Ui.muted(label));return p;}
 private void refresh(){stats.removeAll();stats.add(card("Projects",store.projects().size(),Ui.ACCENT));stats.add(card("Open tasks",(int)store.tasks().stream().filter(x->!x.status().equals("Done")).count(),new Color(46,145,196)));stats.add(card("Open bugs",(int)store.bugs().stream().filter(x->x.status().equals("Open")).count(),new Color(220,92,88)));stats.add(card("Releases",store.versions().size(),new Color(67,168,116)));activity.removeAll();JLabel h=new JLabel("Recent work");h.setFont(new Font("SansSerif",Font.BOLD,18));activity.add(h);activity.add(Box.createVerticalStrut(14));if(store.projects().isEmpty())activity.add(Ui.muted("No projects yet. Open Projects to create your first one."));else for(var p:store.projects().stream().limit(6).toList()){JLabel l=new JLabel("  •  "+p.name()+"  —  "+p.status()+"  ("+p.progress()+"%)");l.setFont(new Font("SansSerif",Font.PLAIN,14));l.setBorder(BorderFactory.createEmptyBorder(7,0,7,0));activity.add(l);}revalidate();repaint();}
}
