name=projyhub
slug=projyhub
language=unknown
status=unknown
main=App
description=No description
source=apps/projyhub
type=data
json=projyhub.json
logs=logs/projyhub.log
files=9
directories=5
size=722907
generated=Aug 17, 11:32:56
