name=Helper
slug=helper
language=Java
status=DEVELOPMENT
main=App
description=No description
source=apps/helper
type=data
json=helper.json
logs=logs/helper.log
files=21
directories=0
size=234514
generated=Aug 17, 11:32:56
